# Site settings
title: Jimmy Qi
email: jimmyqwy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jimmy's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jimmyqwy.github.io/" # the base hostname & protocol for your site
github_username:  jimmyqwy

# Build settings
markdown: kramdown
